### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by akamob** [Darrshan-Sankar/Basic_Gait_analysis-to-confirm.#1]
Hi, Thank you for the great work.

I want to build a gait analysis framework that detect keypoints of human body and distinguish human identity by analyzing their gait. I'm wondering if it is possible that use your code to distinguish human identity and use video as input? Besides, in **Gait_analysis.py** [line 58](https://github.com/Darrshan-Sankar/Basic_Gait_analysis/blob/5908d1118a52f99f9b07a2f99bbe6c0de6cb051c/Gait_analysis.py#L58), you set:
`if x > 70 and y>70 and z>70 and x<=100 and y<=100 and z<=100:`
How to get these parameters? is there any papers or tutorials?

May I have your suggestions?
Any help is much appreciated:)

**Comment by Darrshan-Sankar** [comment]
Yes it is possible to even use video as input, but there are further requirements for the same and I'm to working to implement it and if i find the solution, i will definitely recommit the solution for the same.

And now to the parameters. Here as we already know, we compare the pose estimated dataset output of two gaits , so from the dataset's landmarks we get the x,y, and z params for each gait input. The thing is we just did consider that these values to have a range of 70 to 100 is to make sure that this level of matching is required to say that both the gaits belong to same person, else they are of different persons. 
   This is a basic level of implementation and code improvements are welcomed, which you can leave it here.

**Comment by akamob** [comment]
Hi, thank you for the quick reply:)

If I want to prepare my own data to test, can I use some softwares such as FormatFactory that convert my videos into GIF files? you mentioned the GIF format should have length, frame rate etc.. I'm not sure if this meets the requirements if I use FormatFactory directly.

**Comment by Darrshan-Sankar** [comment]
I'm not sure about that. I used some online softwares to convert videos into GIF's and use them but it didn't work. Give it a try, if it works then it's well and good.

**Comment by akamob** [comment]
Hi, thank you for your reply:)

I will try to test and if I have some new problems then I would contact you again.

Thank you!

**Comment by akamob** [comment]
Hi, @Darrshan-Sankar,

I'm wondering how do you get your GIF files? I try to convert my video into GIF format and run your code, I get:
```
Traceback (most recent call last):
  File "gait_base.py", line 68, in <module>
	for data_point in results.pose_landmarks.landmark:
AttributeError: 'NoneType' object has no attribute 'landmark'
Traceback (most recent call last):
  File "combine_base.py", line 7, in <module>
	for line in open("base1.csv"):
FileNotFoundError: [Errno 2] No such file or directory: 'base1.csv'
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```
![2](https://user-images.githubusercontent.com/49118957/166431052-966e570c-3c55-4375-a669-aa0cd699d09e.jpg)

Then I try to download some GIF files on internet and run your code, but I met same problems. However, I found the same GIF:
![1](https://user-images.githubusercontent.com/49118957/166431624-174cbd94-5adc-4b41-ba03-8442629d6552.jpg)
I download it and run your code successfully. I attempt to use some tools to analyze the GIF attributes:
![3](https://user-images.githubusercontent.com/49118957/166432253-c85bb697-cec3-4952-95a4-1b9498e1ff32.jpg)
But I can't get clue from this information.

May I have your suggestions?
Any help is much appreciated:)

**Comment by Darrshan-Sankar** [comment]
I too have received this error for all the realistic human GIFs and I don't get it why. You can see the keypoints list created to append all the captured landmarks. You can also see that None has been returned on printing the same list. This is because the draw_landmarks didn't do it's work properly. And majorly the pre drw_landmark list is kinda filled with zeroes.

      So we have to resolve this in the draw_landmarks portion of the code. This is the information I have to resolve this problem and I am not in a situation to fix this right now sir. Sorry for the inconveniences. Also you might be able to resolve this with the help of stackoverflow i hope and if you find any result, please update here for the same as it would be useful for me and for others too.

Sorry and thanks

**Comment by akamob** [comment]
Hi, thank you for your reply:)

Ok, I will make more tests and hope to find a solution. If I have some new results then I would contact you again.

Thank you!
